[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'quant-alpha-lab'
version = '0.1.0'
requires-python = '>=3.11'
dependencies=[ 
    # generated via 'pipreqs . --print', then hand-pasted here
    # delete the dependencies if you want to "pip install -e ." to create a package from the project.
    # You may run: python -c "import tomllib; tomllib.load(open('pyproject.toml', 'rb'))" 
    #     to make sure this file is well written before running pip install -e .
    "matplotlib==3.11.1",
    "numpy==2.5.1",
    "pandas==3.0.5",
    "polars==1.43.1",
    "pytest==9.1.1",
    "Requests==2.34.2",
    "tqdm==4.70.0",
    "yfinance==1.5.2",
]

[tool.setuptools]
packages = ['src', 'src.features', 'src.utils', 'config']